version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:latest

    steps:
      - checkout

      - run:
          name: Build image
          command: |
            docker build -t myimage:$(Build.BuildId) -f dockerfile .

      - run:
          name: Run tests
          command: |
            # Add your test commands here

workflows:
  version: 2
  build:
    jobs:
      - build
